# Generated by Django 4.1.9 on 2023-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios_Mala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.IntegerField(verbose_name='COMPET.')),
                ('codigo', models.CharField(max_length=100, verbose_name='CODIGO')),
                ('codigo_fc', models.IntegerField(verbose_name='CODIGO FC')),
                ('aut', models.CharField(max_length=100, verbose_name='Aut')),
                ('data_inicio', models.CharField(max_length=100, verbose_name='Data Inicio')),
                ('data_fim', models.CharField(max_length=100, verbose_name='Data Fim')),
                ('dias_calculados', models.CharField(max_length=100, verbose_name='Dias Calculados')),
                ('tipo_de_beneficio', models.CharField(max_length=100, verbose_name='Tipo de Beneficio')),
                ('valor_pago', models.CharField(max_length=100, verbose_name='Valor Pago')),
                ('data_de_pagamento', models.CharField(max_length=100, verbose_name='Data de Pagamento')),
            ],
            options={
                'ordering': ['comp', 'codigo_fc'],
            },
        ),
    ]
