# Generated by Django 4.1.9 on 2023-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_folha_de_ponto_delete_funcionario_mala'),
    ]

    operations = [
        migrations.AddField(
            model_name='folha_de_ponto',
            name='periodo_apontamento',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
