# Generated by Django 4.1.9 on 2023-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_folha_de_ponto_periodo_apontamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cto',
            field=models.CharField(default='', max_length=100, verbose_name='CONTRATO'),
            preserve_default=False,
        ),
    ]
