# Generated by Django 4.1.9 on 2023-06-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_funcionario_cto'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_1',
            field=models.CharField(default='', max_length=100, verbose_name='DATA 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_2',
            field=models.CharField(default='', max_length=100, verbose_name='DATA 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_3',
            field=models.CharField(default='', max_length=100, verbose_name='DATA 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_4',
            field=models.CharField(default='', max_length=100, verbose_name='DATA 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_5',
            field=models.CharField(default='', max_length=100, verbose_name='DATA 5'),
            preserve_default=False,
        ),
    ]
