# Generated by Django 4.1.9 on 2023-06-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0006_funcionario_data_1_funcionario_data_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='dsr_feriado',
            field=models.CharField(default='', max_length=100, verbose_name='D.S.R. FERIADO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='qtde_dsr_feriado',
            field=models.CharField(default='', max_length=100, verbose_name='QTDE D.S.R FERIADO'),
            preserve_default=False,
        ),
    ]
