# Generated by Django 4.1.9 on 2023-11-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0008_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo_PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30, verbose_name='Matricula')),
                ('auntenticacao', models.CharField(max_length=30, verbose_name='Autenticação')),
                ('competencia', models.CharField(max_length=200)),
                ('coordenadas_x', models.FloatField(blank=True, null=True)),
                ('coordenadas_y', models.FloatField(blank=True, null=True)),
                ('pagina', models.IntegerField(blank=True, null=True)),
                ('arquivo_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf.arquivo')),
            ],
        ),
    ]
