# Generated by Django 4.1.9 on 2023-06-25 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=250)),
                ('cbo', models.CharField(max_length=250)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Salario Hora')),
                ('salario_mes', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Salario Mensal')),
                ('vt', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='VT')),
                ('vr', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='VR')),
                ('cesta', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='CESTA')),
                ('sindicato', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cod_cliente', models.IntegerField()),
                ('responsavel_filial', models.CharField(max_length=250)),
                ('telefone_filial', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='contract_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_departamento', models.CharField(max_length=250)),
                ('endereco_local', models.CharField(max_length=250)),
                ('id_dep_fc', models.CharField(max_length=250)),
                ('cliente_gi_dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissao.clientegi')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('jornada_de_semana', models.CharField(max_length=250)),
                ('periodo_semanal', models.CharField(max_length=250)),
                ('horas_semana', models.CharField(max_length=250)),
                ('jornada_fim_semana', models.CharField(max_length=250)),
                ('periodo_fim_semana', models.CharField(max_length=250)),
                ('horas_fim_semana', models.CharField(max_length=250)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissao.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(max_length=20)),
                ('orgao_emissor_rg', models.CharField(choices=[('SSP', 'Secretaria de Segurança Pública'), ('PM', 'Polícia Militar'), ('PC', 'Polícia Civil'), ('FGTS', 'Fundo de Garantia do Tempo de Serviço'), ('IFP', 'Instituto Félix Pacheco'), ('IPF', 'Instituto Pereira Faustino'), ('IMESP', 'Instituto de Identificação Ricardo Gumbleton Daunt'), ('ITI', 'Instituto de Identificação Tobias de Aguiar'), ('DETRAN', 'Departamento de Trânsito'), ('CTPS', 'Carteira de Trabalho e Previdência Social'), ('FIDENE', 'Fundação de Integração e Desenvolvimento do Ensino do Noroeste do Estado'), ('ME', 'Ministério do Exército'), ('MEX', 'Ministério do Exército'), ('MTE', 'Ministério do Trabalho e Emprego'), ('PF', 'Polícia Federal'), ('POM', 'Polícia Militar'), ('SD/SG', 'Serviço Discreto / Secretaria Geral'), ('SNJ', 'Secretaria Nacional de Justiça'), ('SSPDS', 'Secretaria de Segurança Pública e Defesa da Sociedade'), ('STF', 'Supremo Tribunal Federal'), ('STM', 'Superior Tribunal Militar')], max_length=150)),
                ('uf_rg', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('data_emissao_rg', models.DateField()),
                ('n_ctps', models.CharField(max_length=7)),
                ('serie', models.CharField(max_length=5)),
                ('uf_ctps', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('data_emissao_ctps', models.DateField()),
                ('endereco', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=9)),
                ('celular', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=250)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissao.base')),
                ('cliente_gi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissao.clientegi')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissao.departamento')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissao.turno')),
            ],
        ),
        migrations.AddField(
            model_name='base',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissao.clientegi'),
        ),
    ]
