# Generated by Django 4.1.9 on 2023-06-25 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCNPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('razao', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('avenida_rua', models.CharField(max_length=450, verbose_name='Avenida/Rua')),
                ('endereco', models.CharField(max_length=450, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=90, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=60, verbose_name='Municipio')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=8, verbose_name='Cep')),
                ('nome_cliente', models.CharField(max_length=50, verbose_name='Nome Cliente')),
                ('tipo_de_servico', models.CharField(max_length=5, verbose_name='Tipo de Serviço')),
                ('iss', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ISS')),
                ('unidade', models.CharField(max_length=55, verbose_name='Unidade')),
                ('mcu', models.CharField(max_length=15, verbose_name='MCU')),
                ('tipo_de_cliente', models.CharField(choices=[('LOG', 'LOG'), ('MOT', 'MOT'), ('DISTRIBUIÇÃO', 'DISTRIBUIÇÃO'), ('PRIVADOS', 'PRIVADOS'), ('OUTROS', 'OUTROS')], max_length=150, verbose_name='Tipo de Cliente')),
                ('tx_adm', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='taxa Adm')),
            ],
            options={
                'ordering': ['uf', 'nome_cliente', 'unidade'],
            },
        ),
        migrations.CreateModel(
            name='BaseInfoContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(max_length=5, verbose_name='Cod. Cliente')),
                ('contrato', models.CharField(max_length=65, verbose_name='Contrato')),
                ('cargo', models.CharField(max_length=65, verbose_name='Cargo')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Hora')),
                ('data_inicio_cto', models.DateField(max_length=10, verbose_name='Data Inicio do Contrato no Sistema')),
                ('contrato_ativo', models.BooleanField(verbose_name='Contrato Ativo')),
            ],
            options={
                'ordering': ['cod_cliente', 'contrato', 'cargo'],
            },
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=30, verbose_name='Competência')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquota', models.FloatField()),
                ('cod_atividade', models.CharField(max_length=200)),
                ('cod_obra', models.CharField(max_length=200)),
                ('codigo_autenticidade', models.CharField(max_length=200)),
                ('data_cancelamento', models.DateField()),
                ('data_emissao', models.DateField()),
                ('data_recibo', models.DateField()),
                ('endereco_prestacao_servico', models.CharField(max_length=500)),
                ('link_nfe', models.URLField()),
                ('motivo_cancelamento', models.CharField(max_length=500)),
                ('nome_tomador', models.CharField(max_length=200)),
                ('nosso_numero', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('numero_recibo', models.IntegerField()),
                ('substituicao_tributaria', models.BooleanField()),
                ('valor', models.FloatField()),
                ('valor_iss', models.FloatField()),
                ('valor_nfe', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_de_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('tipo_de_faturamento', models.CharField(choices=[('FATURAMENTO HORAS', 'FATURAMENTO HORAS'), ('FATURAMENTO FG', 'FATURAMENTO FG'), ('FATURAMENTO REPACTUAÇÃO E REQUILIBRIO', 'FATURAMENTO REPACTUAÇÃO E REQUILIBRIO'), ('FATURAMENTO OUTROS', 'FATURAMENTO OUTROS')], max_length=150, verbose_name='Tipo de Faturamento')),
                ('quantidade_hora', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade de Horas')),
                ('quantidade_hora2', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade de Horas 2')),
                ('quantidade_hora3', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade de Horas 3')),
                ('quantidade_hora4', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade de Horas 4')),
                ('quantidade_hora5', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade de Horas 5')),
                ('quantidade_hora6', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade de Horas 6')),
                ('quantidade_hora7', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade de Horas 7')),
                ('quantidade_hora8', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade de Horas 8')),
                ('texto_livre', models.CharField(blank=True, max_length=3500, null=True, verbose_name='Texto Livre')),
                ('contrato_texto_livre', models.CharField(blank=True, max_length=9, null=True, verbose_name='Contrato Texto Livre')),
                ('total_valor_outros', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Valor Outros')),
                ('porcentagem_ans', models.DecimalField(blank=True, decimal_places=2, error_messages={'max_digits': 'Certifique-se de que tenha digitado o valor correto de porcentagem na ANS'}, max_digits=3, null=True, verbose_name='Porcentagem ANS')),
                ('baseinfocontratos', models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.baseinfocontratos')),
                ('baseinfocontratos2', models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_2', to='notas.baseinfocontratos')),
                ('baseinfocontratos3', models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_3', to='notas.baseinfocontratos')),
                ('baseinfocontratos4', models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_4', to='notas.baseinfocontratos')),
                ('baseinfocontratos5', models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_5', to='notas.baseinfocontratos')),
                ('baseinfocontratos6', models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_6', to='notas.baseinfocontratos')),
                ('baseinfocontratos7', models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_7', to='notas.baseinfocontratos')),
                ('baseinfocontratos8', models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_8', to='notas.baseinfocontratos')),
                ('cnpj_da_nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnpj_da_nota', to='notas.basecnpj')),
                ('competencia_nota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.competencias')),
                ('competencia_nota_ans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencia_nota_ans', to='notas.competencias')),
            ],
        ),
    ]
