# Generated by Django 4.1.9 on 2023-06-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal2',
            name='doc_tomador',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
