# Generated by Django 4.1.9 on 2023-06-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_notafiscal2_doc_tomador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal2',
            name='aliquota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='cod_atividade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='cod_obra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='codigo_autenticidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='data_cancelamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='data_recibo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='doc_tomador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='endereco_prestacao_servico',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='link_nfe',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='nome_tomador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='nosso_numero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='numero_recibo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='substituicao_tributaria',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='valor_iss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal2',
            name='valor_nfe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
