# Generated by Django 4.1.9 on 2023-06-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_notafiscal2_aliquota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeradorLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=1)),
            ],
        ),
    ]
