# Generated by Django 4.1.9 on 2023-09-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_numeradorlote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecnpj',
            name='iss',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='ISS'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_2', to='notas.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_3', to='notas.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_4', to='notas.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_5', to='notas.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_6', to='notas.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_7', to='notas.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_8', to='notas.baseinfocontratos'),
        ),
    ]
