# Generated by Django 4.1.9 on 2023-09-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_notas_nota_cancelada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota_cancelada',
            field=models.BooleanField(default=False, verbose_name='Nota Cancelada?'),
        ),
    ]
