# Generated by Django 4.1.9 on 2023-09-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_alter_notas_nota_cancelada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecnpj',
            name='tx_adm',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='taxa Adm'),
        ),
    ]
